project:
  type: book
  output-dir: docs
filters:
  - webr
webr:
  packages: ['tidyverse']

book:
  title: "Computational-Statistics"
  author: "Nina Leach"
  
  chapters:
    - index.qmd
    - part: "Background"
      chapters: 
        - probability.qmd
    - part: "Generating Random Numbers"
      chapters:
        - summary.qmd
        
  appendices: 
    - howto.qmd
  
  search: true
  repo-url: https://github.com/N-Leach/course_Computational-Statistics
  downloads: [pdf]

#bibliography: references.bib

format:
  html:
    theme: materia
  pdf:
    documentclass: scrreprt

editor: visual