project:
  type: book
  output-dir: docs
filters:
  - webr
webr:
  packages: ['palmerpenguins', "HistData"]

book:
  title: "Computational-Statistics"
  author: "Nina Leach"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
  
  search: true
  repo-url: https://github.com/N-Leach/course_Computational-Statistics
  downloads: [pdf]

#bibliography: references.bib

format:
  html:
    theme: materia
  pdf:
    documentclass: scrreprt

editor: visual